-- MySQL Script generated by MySQL Workbench
-- jeu. 30 août 2018 10:01:11 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cogip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cogip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cogip` DEFAULT CHARACTER SET utf8 ;
USE `cogip` ;

-- -----------------------------------------------------
-- Table `cogip`.`typeEntreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`typeEntreprise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cogip`.`societes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`societes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  `pays` VARCHAR(255) NOT NULL,
  `numTva` VARCHAR(50) NOT NULL,
  `numTel` VARCHAR(20) NOT NULL,
  `typeEntreprise_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_societes_typeEntreprise_idx` (`typeEntreprise_id` ASC),
  CONSTRAINT `fk_societes_typeEntreprise1`
    FOREIGN KEY (`typeEntreprise_id`)
    REFERENCES `cogip`.`typeEntreprise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cogip`.`personnes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`personnes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  `numTel` VARCHAR(20) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `societes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personnes_societes_idx` (`societes_id` ASC),
  CONSTRAINT `fk_personnes_societes`
    FOREIGN KEY (`societes_id`)
    REFERENCES `cogip`.`societes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cogip`.`tva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`tva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tauxTva` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cogip`.`factures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`factures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `dateFact` DATE NOT NULL,
  `numCommande` VARCHAR(255) NULL,
  `objet` VARCHAR(255) NULL,
  `societes_id` INT NOT NULL,
  `personnes_id` INT NOT NULL,
  `tva_id` INT NOT NULL,
  INDEX `fk_factures_societes_idx` (`societes_id` ASC),
  INDEX `fk_factures_personnes_idx` (`personnes_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_factures_tva_idx` (`tva_id` ASC),
  CONSTRAINT `fk_factures_societes`
    FOREIGN KEY (`societes_id`)
    REFERENCES `cogip`.`societes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factures_personnes`
    FOREIGN KEY (`personnes_id`)
    REFERENCES `cogip`.`personnes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factures_tva`
    FOREIGN KEY (`tva_id`)
    REFERENCES `cogip`.`tva` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cogip`.`Produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`Produits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(255) NOT NULL,
  `prixUnitaire` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cogip`.`detailsFacture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`detailsFacture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numLigne` INT NOT NULL,
  `quantite` INT NOT NULL,
  `prixFactHT` DOUBLE NOT NULL,
  `remiseHT` DOUBLE NULL,
  `factures_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detailsFacture_factures_idx` (`factures_id` ASC),
  CONSTRAINT `fk_detailsFacture_factures`
    FOREIGN KEY (`factures_id`)
    REFERENCES `cogip`.`factures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cogip`.`Produits_has_detailsFacture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`Produits_has_detailsFacture` (
  `Produits_id` INT NOT NULL,
  `detailsFacture_id` INT NOT NULL,
  PRIMARY KEY (`Produits_id`, `detailsFacture_id`),
  INDEX `fk_Produits_has_detailsFacture_detailsFacture_idx` (`detailsFacture_id` ASC),
  INDEX `fk_Produits_has_detailsFacture_Produits_idx` (`Produits_id` ASC),
  CONSTRAINT `fk_Produits_has_detailsFacture_Produits`
    FOREIGN KEY (`Produits_id`)
    REFERENCES `cogip`.`Produits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produits_has_detailsFacture_detailsFacture`
    FOREIGN KEY (`detailsFacture_id`)
    REFERENCES `cogip`.`detailsFacture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
